inherit_from: .rubocop_todo.yml

# TODO: 後でコメントを削除
# 追加した規約ファイル読込
require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
    - "vendor/**/*"
    - "Gemfile.lock"

# 1行が長すぎる
Layout/LineLength:
  Max: 200

# 未使用の引数チェック
Lint/UnusedMethodArgument:
  Enabled: false

# 開発者が感じていたプログラムの 匂い を定量的に判断する
# Offense count: 2
# default 15
Metrics/AbcSize:
  Max: 29

# Metrics/BlockLength: Block has too many lines.　を無視
Metrics/BlockLength:
  Enabled: false

# ネストを許可する深さ
Metrics/BlockNesting:
  Max: 5

# メソッドの行数が長すぎる
Metrics/MethodLength:
  Enabled: false

# 引数の数が多すぎる
Metrics/ParameterLists:
  Max: 12

# migration高速化のための設定
# テーブル作成、テーブルカラム編集
Rails/BulkChangeTable:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

#  capybara固有のメソッドを有効にする
RSpec/Capybara:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/requests/*.rb
    - spec/requests/*/*.rb

RSpec/NamedSubject:
  Enabled: false

RSpec/ReturnFromStub:
  EnforcedStyle: block

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
