inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.5.7
  # 除外(RuboCopで解析させないフォルダ、ファイル群)
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/**/*'
    - 'Gemfile.lock'
  # rubocop ver0.72 以降は使わない(代わりにrequire rubocop-rails)
  # Rails:
  #   enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics/BlockLength: Block has too many lines.　を無視
Metrics/BlockLength:
  Enabled: false

# ネストを許可する深さ
BlockNesting:
  Max: 5

# 開発者が感じていたプログラムの 匂い を定量的に判断する
# Offense count: 2
# default 15
Metrics/AbcSize:
  Max: 29

# 1行が長すぎる
Layout/LineLength:
  Max: 120

# メソッドの行数が長すぎる
MethodLength:
  Enabled: false

# 引数の数が多すぎる
ParameterLists:
  Max: 12

Style/StringLiterals:
  Enabled: false

# RSpecの設定
#  capybara固有のメソッドを有効にする
Capybara/FeatureMethods:
  Enabled: false

# 未使用の引数チェック
Lint/UnusedMethodArgument:
  Enabled: false


# migration高速化のための設定
# テーブル作成、テーブルカラム編集
Rails/BulkChangeTable:
  Enabled: false


RSpec/ExampleLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/requests/*.rb
    - spec/requests/*/*.rb

RSpec/ContextWording:
  Enabled: false
