version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
        - "4306:3306"
    volumes:
        - db-data:/var/lib/mysql
  web:
    init: true
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/webapp
      - bundle:/usr/local/bundle
      - node-modules:/webapp/node_modules
    ports:
      - "3000:3000"
      - "3035:3035"
    links:
      - db
      # - chrome
    environment:
      RAILS_ENV: development
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/webapp.conf
      # - public-data:/webapp/public
      # - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - web
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5901:5900

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
  node-modules:
    driver: local
